### ISSUE TITLE
PostController for article

### ISSUE THREAD

**Issue by ghost** [wi2/isomorphic-sails-react-example#1]
From the Post controller, the article end with a real time issue. 

Removing the {title:post.title} fixed it.

**Comment by wi2** [comment]
Really..it's weard..

So.. it's not a good approach to use renderTo service.. 
i prefer use a response approach, see : 
https://github.com/wi2/calendar-example/blob/master/api/responses/react.js
and how tu use : https://github.com/wi2/calendar-example/blob/master/api/controllers/HomeController.js

Thanks
Mike

**Comment by ghost** [comment]
Hi Mike,

Response look like a better approach, I'll give it a try.

Thanks

**Comment by wi2** [comment]
cool.. It's a pleasure..
i think so too..

**Comment by ghost** [comment]
Rendering the home via response.react work, 
unfortunately I also got a `TypeError: type.toUpperCase is not a function`

**Comment by wi2** [comment]
I hope..
you have component not starting with uppercase : 
mycomponent  => Mycomponent

**Comment by naptiv** [comment]
No, 
When I remove /componnent/app.js it's render without the TypeError.
But if I remove the app.js the rendered componnent didn't change on state updates

**Comment by naptiv** [comment]
I've tried to implement the calendar browserify, and package.json script but now I've got a 
`Error: _registerComponent(...): Target container is not a DOM element.`

**Comment by ghost** [comment]
No was a bit tricker 
check : https://github.com/wi2/calendar-example/issues/1

**Comment by wi2** [comment]
ok.. thanks.. I check that
